### ISSUE TITLE
Error Upon First Startup of .bat

### ISSUE THREAD

**Issue by Zeprido** [MistyKnives/Kick-Discord-RPC#3]
ERROR: The system was unable to find the specified registry key or value.
'java' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

Then the program exits itself. I was never presented a prompt to download java as described in the guide.

![error kick discord](https://github.com/MistyKnives/Kick-Discord-RPC/assets/48721255/f964486a-8231-45f5-9630-6f7b2529d064)

After manually installing Java 19, it displayed a similar message of:
ERROR: The system was unable to find the specified registry key or value.

but then worked as intended and produced results and expected actions as intended.

**Comment by tyyzf** [comment]
Errors:
 - "Java is not recongized" is due to you not having Java on your system. please install Java 19 as intended.
 - "Unable to find the specified registry key or value" is for the system to check if you have Java on your system, ignore it. As long as you have Java on your system, it will work as intended. If you have any other issues please do not be afraid to contact me!
